# Generated by Django 4.1.7 on 2023-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_photo_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='email',
            field=models.EmailField(default='jacob.d.frazer@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sale',
            name='card_number',
            field=models.CharField(default='1234123412341234', max_length=16),
        ),
        migrations.AlterField(
            model_name='sale',
            name='code',
            field=models.CharField(default='123', max_length=3),
        ),
    ]
