# Generated by Django 4.1.7 on 2023-02-21 17:15

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_sale_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='card_number',
            field=models.PositiveBigIntegerField(default='1234123412341234', validators=[events.models.validate_card_number]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='code',
            field=models.PositiveSmallIntegerField(default='123', validators=[events.models.validate_card_code]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='expiry_date',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
